import "./styles/globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import { Providers } from "./GlobalRedux/provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
